### ISSUE TITLE
Sentence ordering may be relooked at section 2.1

### ISSUE THREAD

**Issue by sambitdash** [sisl/algorithmsbook#18]
Section 2.1 Degrees of Belief and Probability

The three sentences below may be reorganized. What are A and B. Followed by how to represent A > B and A == B. The flow below may be a bit out of sync. 

> We would like to be able to represent, for example, that the plausibility of a proposition A is greater than the plausibility of another proposition B. If A represents ‘‘I will wear a coat’’, and B represents ‘‘it will rain’’, then we would write A  B. If we believe A and B are equally plausible, then we write A  B.

**Comment by mykelk** [comment]
Reworked as follows:
![image](https://user-images.githubusercontent.com/6294079/104138522-6fee1200-5359-11eb-88f9-260e04d7b2b5.png)
It's easier on the reader, I think, to introduce an example and then specify the general notation. Also changed the example to reduce the risk of confusion (since we have control over whether we will wear a coat).
